//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HastaneOtomasyonu
{
    using System;
    using System.Collections.Generic;
    
    public partial class Doktorlar
    {
        public string DoktorTC { get; set; }
        public string DoktorAd { get; set; }
        public string DoktorSoyad { get; set; }
        public int BolumID { get; set; }
        public Nullable<int> DoktorYas { get; set; }
        public string DoktorTelefon { get; set; }
    
        public virtual Bolumler Bolumler { get; set; }
    }
}
